version: 5
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: addons
  password: aiPa0zaequ8phaezieph4ieB6choonaiseineileipo6UuTeitahp7aig8ui6ou1
serial:
  port: /dev/ttyUSB0
  adapter: ember
  baudrate: 115200
  rtscts: false
advanced:
  log_level: debug
  channel: 11
  network_key:
    - 54
    - 167
    - 205
    - 213
    - 38
    - 216
    - 66
    - 60
    - 144
    - 205
    - 94
    - 13
    - 26
    - 131
    - 135
    - 9
  pan_id: 57535
  ext_pan_id:
    - 211
    - 120
    - 247
    - 239
    - 199
    - 183
    - 245
    - 247
  elapsed: true
  log_directories_to_keep: 351
  last_seen: ISO_8601
frontend:
  enabled: true
  port: 8099
homeassistant:
  enabled: true
devices:
  '0xa4c138707147732e':
    friendly_name: Smart_Bulb
  '0xa4c1384da3ad1b38':
    friendly_name: Sensor
  '0x0c4314fffe54b110':
    friendly_name: Smart_Plug
availability:
  enabled: true
device_options:
  homeassistant:
    last_seen:
      enabled_by_default: true
